DBD/DBD/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("dbd_stats.urls")),
    path("admin/", admin.site.urls),
    path('api/', include('rest_framework.urls')),
]

DBD/dbd_stats/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = "DBD_tracker"
urlpatterns = [
    path("", views.index, name="index"),
    path("submit_data", views.get_game_data, name="submit_data"),
    path("submit_data/thanks", views.thanks, name="Thanks"),
    path('stats/', views.statistics, name='stats'),

    path("api",views.game_list.as_view()),
    path("api/<int:pk>/", views.GamesDetail.as_view()),

]

urlpatterns = format_suffix_patterns(urlpatterns)

DBD/dbd_stats/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


killer_choices = (
    ("The Trapper","The Trapper"),
    ("The Hillbilly","The Hillbilly"),
    ("The Hag","The Hag"),
    ("Huntress","Huntress"),
    ("Micheal Myers","Micheal Myers",),
    ("The Plague","The Plague"),
    ("The spirit","The spirit"),
    ("The Oni","The Oni"),
    ("The Legion","The Legion"),
    ("The Artist","The Artist"),
    ("ghost face","ghost face"),
    ("The Cannibal","The Cannibal"),
    ("The pig","The pig"),
    ("The Doctor","The Doctor"),
    ("The Nurse","The Nurse"),
    ("Nemesis","Nemesis"),
    ("Demogorgon", "Demodogo"),
    ("The Trickster","The Trickster"),
    ("The Blight","The Blight"),
    ("The Cenobite","The Cenobite"),
    ("Freddy Krueger","Freddy Krueger"),
    ("The Clown","The Clown"),
    ("The Wraith","The Wraith"),
    ("The Twins","The Twins"),
    ("Pyramid head","Pyramid head"),
    ("DeathSlinger","DeathSlinger"),
    ("The knight","The knight"),
    ("The skull merchant","The skull merchant"),
    ("Dredge","Dredge"),
    ("Mastermind","Mastermind"),
    ("The Onryo","The Onryo"))

map_choices=(
    ("Raccoon City","Raccoon City"),
    ("Midwitch elementary school","Midwitch elementary school"),
    ("Garden of Joy","Garden of joy"),
    ("The MacMillan Estate","The MacMillan Estate"),
    ("Autohaven Wreckers","Autohaven Wreckers"),
    ("Coldwind Farm","Coldwind Farm"),
    ("Crotus Prenn Asylum","Crotus Prenn Asylum"),
    ("Haddonfield","Haddonfield"),
    ("Backwater Swamp","Backwater Swamp"),
    ("Léry's Memorial Institute","Léry's Memorial Institute"),
    ("Red Forest","Red Forest"),
    ("Springwood","Springwood"),
    ("Gideon Meat Plant","Gideon Meat Plant"),
    ("Yamaoka Estate","Yamaoka Estate"),
    ("Ormond","Ormond"),
    ("Grave of Glenvale","Grave of Glenvale"),
    ("Silent Hill","Silent Hill"),
    ("Forsaken Boneyard","Forsaken Boneyard")


)

faul_play_Choices = (
    ("face camping","face camping"),
    ("Tunneling","Tunneling"),
    ("NA","NA"),
    ("camping","camping")
)
mood_players = (("FUN","FUN"),
             ("Irritated","rritated"),
             ("tired","tired"),
             ('meh',"meh"),
             )

play_style_choices = (("normal", "normal"),
                      ("meme","meme"),
                      ("Sweat","sweat"),
                      ("Challanges","challanges"))
class Game(models.Model):

    pub_date = models.DateTimeField("date published")
    killer = models.CharField(max_length=24, choices=killer_choices,default="The Trapper")
    mori = models.BooleanField(default=False)
    Insta_down = models.BooleanField(default=False)
    sweat = models.IntegerField(default=5,validators=[MinValueValidator(0),MaxValueValidator(10)])
    Game_map = models.CharField(max_length=26, choices=map_choices, default="Raccoon City")
    deaths =  models.IntegerField(default=4,validators=[MinValueValidator(0),MaxValueValidator(4)])
    Gens_completed =  models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(5)])
    Faul_play = models.CharField(max_length=20, choices=faul_play_Choices, default="NA")
    overal_fun = models.IntegerField(default=5,validators=[MinValueValidator(0),MaxValueValidator(10)])
    player_1 = models.CharField(max_length=9, choices=mood_players,default="FUN")
    player_2 = models.CharField(max_length=9, choices=mood_players,default="FUN")
    player_3 = models.CharField(max_length=9, choices=mood_players,default="FUN")
    player_4 = models.CharField(max_length=9, choices=mood_players,default="FUN")
    overall_play_style = models.CharField(max_length=10, choices=play_style_choices,default="normal")


    def __str__(self):
        return f"{self.killer}_{self.pub_date}"

    def max_death(self):
        return self.deaths <= 4

    def max_gens(self):
        return self.Gens_completed <= 5

    class Meta:
        ordering = ["pub_date"]

DBD/dbd_stats/forms.py
from .models import Game
import datetime
from django.forms import ModelForm, Textarea
class Game_form_entree(ModelForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['pub_date'].initial = datetime.datetime.now()
    class Meta:
        model = Game
        fields = "__all__"

DBD/dbd_stats/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from rest_framework.decorators import api_view
from django.shortcuts import render
from .forms import Game_form_entree
import datetime
from rest_framework.renderers import JSONRenderer

from django.http import HttpResponse, JsonResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Game
from .serializers import GameSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status,mixins, generics
from .utils import *


# Include the `fusioncharts.py` file that contains functions to embed the charts.

def index(request):
    return render(request, "dbd_stats/welcome_page.html")


def get_game_data(request):
    initial_data ={"pub_date":datetime.now()}
    if request.method == "POST": #data send by user
        form = Game_form_entree(request.POST,initial=initial_data)        # create a form instance and populate it with data from the request:

        # check whether it's valid:
        if form.is_valid():
            form.save() #safe data to database
            # redirect to a new URL:
            return HttpResponseRedirect("submit_data/thanks")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = Game_form_entree()

    context = {"dbd_form": form}
    return render(request, "dbd_stats/form_template.html", context=context)

def thanks(request):

    return  render(request, "dbd_stats/form_succes.html")

#adding

def statistics(request):
    serializer = GameSerializer(Game.objects.all(), many=True)
    data = (serializer.data)
    data = CreateData((data))
    context = {"games_a_day": data.get_plot_histogram()}

    return render(request, "dbd_stats/statistics.html",context=context)


class game_list(generics.ListCreateAPIView):
    queryset = Game.objects.all()
    serializer_class = GameSerializer

class GamesDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Game.objects.all()
    serializer_class = GameSerializer

DBD/dbd_stats/templates/dbd_stats/form_succes.html
<!DOCTYPE html>
    {% load static %}

<html>
<head>
    <title>Thanks for Submitting!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dbd_stats/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Thanks for Submitting!</h1>
        <p>Your game data has been successfully submitted.</p>
        <div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/kApu770jYmBdpzx81U" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/xbox-game-xbox-series-x-s-kApu770jYmBdpzx81U"></p>
        <style>
        .submit-button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .submit-button:hover {
            background-color: #45a049;
        }
        </style>

        <a class="submit-button" href="{% url 'DBD_tracker:index' %}">Return home</a>
    </div>
</body>

DBD/dbd_stats/templates/dbd_stats/form_template.html
<html>
    {% load static %}

<head>
    <title>Dead by Daylight Match Stats Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dbd_stats/style.css' %}">

</head>
<body>
    <form action="submit_data" method="post">
        {% csrf_token %}
        <h1>Dead by Daylight Match Stats Form</h1>
            {{ dbd_form.as_ul  }}

        <style>
        .submit-button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .submit-button:hover {
            background-color: #45a049;
        }
        </style>
        <input class="submit-button" type="submit" value="Save New DBD Data">
    </form>
</body>
</html>

DBD/dbd_stats/templates/dbd_stats/statistics.html
<html>
    {% load static %}

<head>
    <title>Statistics</title>
    <link rel="stylesheet" type="text/css" href="{% static 'dbd_stats/style.css' %}">
</head>
<body>
 <img src="data:image/png;base64,{{games_a_day|safe}}" >
</body>
</html>

DBD/dbd_stats/templates/dbd_stats/welcome_page.html
<!DOCTYPE html>
    {% load static %}

    <html>
    <head>
        <title>Dead by Daylight Django App</title>
        <link rel="stylesheet" type="text/css" href="{% static 'dbd_stats/style.css' %}">
    </head>
    <body>
        <header>
            <h1 class="logo">Dead by Daylight Tracker</h1>
            <nav>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="stats">Statistics</a></li>
                    <li><a href="submit_data">Submit Data</a></li>
                </ul>
            </nav>
        </header>

        <div class="container">
            <section id="hero">
                <h2>Welcome to Dead by Daylight tracker!</h2>
                <p>Track and analyze your gameplay data.</p>
            </section>

            <section id="statistics">
                <h2>Statistics</h2>
                <!-- Display statistics here -->
            </section>

            <section id="submit-data">
                <h2>Submit Game Data</h2>
                <!-- Display the form for submitting game data here -->
            </section>
        </div>

        <footer>
            <p>&copy; 2023 Dead by Daylight Tracker. All rights reserved.</p>
        </footer>
    </body>
</html>